name = "Obelisktest"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9afc8af6dd6866790f8abbab861e2ad999b0fe244e2a2856b8a7bb4c8c2490b5"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
