name = "Obelisktest"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eccd189a17098f116da561fc2d121d2cad283fddedebf4ced0d138cc4fc04a63"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
