name = "Obelisktest"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bda8b26c03f24fd5830c7bc1a07b750b9249e0f590374b3556b60a3988d5ec22"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
