name = "Obelisktest"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7664b8def457a0f8cc5b57b4e8ab92f22d1e0277286102a34b03d8f221a555b9"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
