modLoader="lowcodefml"
loaderVersion="[1,)"
license="Stardust Labs License"
issueTrackerURL="https://github.com/Stardust-Labs-MC/Continents/issues"

[[mods]]
    modId="continents"
    version="1.1.11"
    displayName="Continents"
    displayURL="https://www.stardustlabs.net/"
    logoFile="pack.png"
    authors="Stardust Labs"
    credits="Starmute: Owner. catter1: Maintainer."
    description="Reshapes the world to consist of continents, separated by large oceans and small islands."

[[dependencies.continents]]
    modId="forge"
    mandatory=false
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.continents]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.22)"
    ordering="NONE"
    side="BOTH"