
["Main Toggles"]
	#Allows partial health recovery by eating partial health recovery items. (Default: true)
	"Toggle Partial Health Recovery" = true
	#Allows full health recovery by eating full health recovery items. (Default: true)
	"Toggle Full Health Recovery" = true
	#Allows passive health recovery every full Minecraft day. (Default: true)
	"Toggle Passive Health Recovery" = true
	#Allows health recovery when sleeping through the night. (Default: true)
	"Toggle Sleep Health Recovery" = false
	#Enables recovery mechanic after multiple consecutive deaths at 1 HP with a cooldown. (Default: true)
	"Toggle Determination" = false

["Minor Toggles"]
	#Should the passive recovery timer reset when you die. (Default: true)
	"Reset Passive Recovery on Death" = true
	#Should deaths count toward determination even while it is on cooldown. (Default: true)
	"Deaths Count While Determination is on Cooldown" = true
	#Toggle whether satisfying a craving restores some of your health if mod Cravings! is installed. (Default: true)
	"Cravings! compatibility toggle" = true

["Health Recovery Items"]
	#Items that, when consumed, partially restore your original max health.
	"Partial Health Recovery Items" = ["minecraft:golden_apple"]
	#Items that, when consumed, fully restore your original max health.
	"Full Health Recovery Items" = ["minecraft:enchanted_golden_apple"]

["Max Health"]
	#Your original max health. Used to calculate loss, recovery, and cap (default: 20).
	#Use to gain extra hearts. Not compatible (yet) with mods that alter health.
	#Range: 1 ~ 512
	"Max Default Health" = 20

["Timers and Cooldowns"]
	#Time in ticks before passive recovery triggers again. (Default: 24000 = 1 full Minecraft day)
	#Range: > 0
	"Time Between Recoveries" = 24000
	#Number of consecutive deaths at 1 health before Determination activates. (Default: 3)
	#Range: > 1
	"Deaths for Determination" = 3
	#Cooldown time in ticks before Determination can trigger again. (Default: 12000 = half a day)
	#Range: > 1
	"Determination Cooldown" = 12000

["Health loss and recovery percentages"]
	#Percentage of your current max health lost on death. Set to 0 to disable. (Default: 50)
	#Range: 0 ~ 100
	"Health Lost on Death" = 10
	#Percentage of your max health restored when using partial recovery items. (Default: 25)
	#Range: 1 ~ 100
	"Partial Health Recovered" = 25
	#Percentage of your max health restored after surviving a full Minecraft day. (Default: 5)
	#Range: 1 ~ 100
	"Passive Health Recovered" = 15
	#Percentage of your max health restored by sleeping. (Default: 5)
	#Range: 1 ~ 100
	"Sleep Health Recovered" = 5
	#Percentage of your max health restored via Determination. (Default: 15)
	#Range: 1 ~ 100
	"Determination Health Recovered" = 15
	#Percentage of your max health restored by satisfying a craving if the mod Cravings! is installed. (Default: 5)
	#Range: 1 ~ 100
	"Craving Satisfied Health Recovered" = 5

["Grace settings"]
	#Determines whether sleeping grants the player the Grace effect upon waking.
	#This effect protects them from losing max health on their next death. (default: true
	"Sleep Grace Toggle" = true
	#Sets how long the Grace effect from sleeping will last, in ticks. (Default: 2400)
	#Range: > 0
	"Sleep Grace Duration" = 2400
	#Determines whether the player receives the Grace effect after their first death from full health. (default: true)
	"Grace on First Death Toggle" = true
	#Sets how long the Grace effect from dying on full health will last, in ticks. (Default: 6000)
	#Range: > 0
	"Grace on First Death Duration" = 6000
	#Determines whether triggering Determination also grants the Grace effect. (Default: true
	"Grace from Determination" = true
	#Sets how long the Grace effect from Determination will last, in ticks. (Default: 2400)
	#Range: > 0
	"Grace from Determination Duration" = 2400

["Hardmode settings"]
	#The amount of damage that must be acumulated to lose health. (default: 10)
	#Range: > 1
	"HardMode Threshold" = 10
	#The amount of damage the threshold will be reduced by every second. (default: 0.5)
	#Range: 0.0 ~ 100.0
	"Threshold Decay" = 0.5
	#The time interval (in ticks) between each reduction of accumulated damage.
	#Set to very big if you don't want any decay.
	#20 ticks = 1 second. (Default: 40)
	#Range: > 1
	"Threshold Decay Interval" = 40
	#If enabled, the timer that reduces accumulated damage will reset each time the player takes damage. (Default: true)
	"Threshold Decay Reset" = true
	#Percentage of max health lost per hit when Hardmode is active. (Default: 10)
	#Range: 1 ~ 100
	"Hardmode Health Loss" = 10
	#When enabled, all damage added to the HardMode threshold ignores armor, resistance, and other reductions.
	#While this makes HardMode more punishing, it also ensures damage tracking is more consistent and stable. (Default: false)
	"True Damage" = false
	#Disable the new threshold system to use a chance-based HardMode, where there is a chance you lose health everytime you receive a hit. (default: false)
	"Old HardMode" = false
	#Chance to lose max health when damaged while Hardmode is active. (Default: 100)
	#This does not need to be lowered to earn the 'Dumb Luck' achievement.
	#Range: 0 ~ 100
	"Hardmode Chance" = 100

["Miscellaneous configs"]
	#Show a warning on world load if ModernFix is installed.
	#This mod normally updates config values during gameplay, but ModernFix prevents this.
	#If you are using ModernFix and change any config values, a full game restart will be required.
	#The mod will still work as intended with ModernFix installed.
	"Show ModernFix warning" = true

