
["dRandomSpawn Config"]
	#The maximum radius, in blocks, from the world spawn for random teleportation.
	#Must have a higher value than minDistance.
	#Default:
	#maxDistance = 5000
	#Range: 1 ~ 50000
	maxDistance = 500
	#The minimum radius, in blocks, from the world spawn for random teleportation.
	#Must have a lower value than maxDistance.
	#Default:
	#minDistance = 500
	#Range: 1 ~ 50000
	minDistance = 50
	#How many times the mod will try to find a safe location within the maxDistance.
	#If all attempts fail, the player will spawn at the default world spawn.
	#Default:
	#maxTries = 50
	#Range: 1 ~ 100
	maxTries = 50
	#A list of biomes where new players are not allowed to spawn.
	#Entries must be valid biome resource locations, e.g., 'minecraft:ocean' or 'biomesoplenty:wasteland'.
	#Default: 
	#biomeBlacklist = []
	biomeBlacklist = []
	#A list of blocks that players cannot spawn directly on top of.
	#This is useful for preventing spawns on dangerous blocks.
	#Entries must be valid block resource locations, e.g., 'minecraft:lava'.
	#Default:
	#blockBlacklist = ["minecraft:water", "minecraft:lava", "minecraft:magma_block", "minecraft:cactus", "minecraft:sweet_berry_bush"]
	blockBlacklist = ["minecraft:water", "minecraft:lava", "minecraft:magma_block", "minecraft:cactus", "minecraft:sweet_berry_bush"]
	#If true, puts a player into spectator mode and applies a darkness effect while finding a safe spawn.
	#This prevents them from moving and hides world loading, providing a smoother experience.
	#Default:
	#useSpectatorLock = true
	useSpectatorLock = true

